USE tinderdome;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	remember_token VARCHAR(100),
	email VARCHAR(255),
	number_people INT,
	gender VARCHAR(1),
	height INT,
	birth_year INT,
	description VARCHAR(2000),
	how_to_find_me VARCHAR(200),
	number_photos INT,
	random_ok BOOLEAN,
	hoping_to_find_acquaintance BOOLEAN,
	hoping_to_find_friend BOOLEAN,
	hoping_to_find_love BOOLEAN,
	hoping_to_find_lost BOOLEAN,
	hoping_to_find_enemy BOOLEAN,
	attending_winter_games BOOLEAN,
	attending_ball BOOLEAN,
	attending_detonation BOOLEAN,
	attending_wasteland BOOLEAN,
	ip VARCHAR(50),
	created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO users (
	name,
	password,
	email,
	number_people,
	gender,
	height,
	birth_year,
	description,
	how_to_find_me,
	number_photos,
	random_ok,
	hoping_to_find_acquaintance,
	hoping_to_find_friend,
	hoping_to_find_love,
	hoping_to_find_lost,
	hoping_to_find_enemy,
	attending_winter_games,
	attending_ball,
	attending_detonation,
	attending_wasteland,
	ip
) VALUES (
	'Firebird',
	'changeme',
	'wastelandfirebird@gmail.com',
	1,
	'M',
	NULL,
	1970,
	"I'm a member of both the F-Birds and the Seagull Clan. I'm a driver. I take things to people and people to places. I'm rebuilding society from its ashes, but this time without governments or wars. I'm the creator of the You Are Awaited mission. If you find your match and your match is willing, you and your match can come find me together and tell me your story. I'll reward you with special bottle caps. HARMONIA ABSQUE IMPERIO. SPEED THE FUCK UP.",
	'Look for the Firebird on the back of my jacket.',
	5,
	TRUE,
	TRUE,
	TRUE,
	FALSE,
	FALSE,
	FALSE,
	TRUE,
	TRUE,
	TRUE,
	TRUE,
	'localhost'
);
