USE tinderdome;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	remember_token VARCHAR(100),
	email VARCHAR(255) UNIQUE NOT NULL,
	number_people INT NOT NULL,
	gender VARCHAR(1),
	gender_of_match VARCHAR(1),
	gender_of_match_2 VARCHAR(1),
	height INT,
	birth_year INT,
	description VARCHAR(2000),
	how_to_find_me VARCHAR(200),
	number_photos INT,
	random_ok BOOLEAN,
	hoping_to_find_friend BOOLEAN,
	hoping_to_find_love BOOLEAN,
	hoping_to_find_lost BOOLEAN,
	hoping_to_find_enemy BOOLEAN,
	share_info_with_favorites BOOLEAN,
    title_index INT,
	ip VARCHAR(50) NOT NULL,
	created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_active timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	greylist INT
);
